---
- name: install python3
  become: yes
  package:
    name: "{{item}}"
    state: present
  with_items:
    - python3-minimal
    - python3-pip

- name: update-alternatives install python2
  become: yes
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python2
    priority: 30
  check_mode: no

# last executed one gets also set
- name: update-alternatives install python3 (default)
  become: yes
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
    priority: 70

- name: update-alternatives install pip2
  become: yes
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip2
    priority: 30
  check_mode: no
  when: not (ignore_pip2 | bool)

# last executed one gets also set
- name: update-alternatives install pip3 (default)
  become: yes
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3
    priority: 70
