---
- name: is python2 installed
  stat:
    path: /usr/bin/python2
  register: py2_stat_result

- name: configure python3 as default python
  block:
    - name: try package installation method
      import_tasks: package.yml
  rescue:
    - name: use update alternatives method
      import_tasks: alternatives.yml
  when:
    - python3_default_try_package_method | bool
    - py2_stat_result.stat.exists

- name: use update alternatives method
  import_tasks: alternatives.yml
  when:
    - not python3_default_try_package_method | bool
    - py2_stat_result.stat.exists
